# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simple_param_popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow
from gui import Ui_MainWindow

class Dialog(QMainWindow):
    def setupUi(self, MainWindow, Ui_MainWindow):
        MainWindow.setObjectName("Set search parameters")
        MainWindow.resize(480, 375)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(60, 220, 131, 20))
        self.label_6.setObjectName("label_6")
        self.le_false_negative_penalty = QtWidgets.QLineEdit(self.centralwidget)
        self.le_false_negative_penalty.setGeometry(QtCore.QRect(214, 220, 113, 20))
        self.le_false_negative_penalty.setObjectName("le_false_negative_penalty")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(230, 280, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.pushButton.clicked.connect(Ui_MainWindow.listener_param_fitting_basic_dialog_clicked) # added manually

        self.le_threshold_from = QtWidgets.QLineEdit(self.centralwidget)
        self.le_threshold_from.setGeometry(QtCore.QRect(214, 20, 113, 20))
        self.le_threshold_from.setObjectName("le_threshold_from")
        self.le_threshold_step = QtWidgets.QLineEdit(self.centralwidget)
        self.le_threshold_step.setGeometry(QtCore.QRect(214, 100, 113, 20))
        self.le_threshold_step.setObjectName("le_threshold_step")
        self.le_min_dice = QtWidgets.QLineEdit(self.centralwidget)
        self.le_min_dice.setGeometry(QtCore.QRect(214, 140, 113, 20))
        self.le_min_dice.setObjectName("le_min_dice")
        self.le_threshold_to = QtWidgets.QLineEdit(self.centralwidget)
        self.le_threshold_to.setGeometry(QtCore.QRect(214, 60, 113, 20))
        self.le_threshold_to.setObjectName("le_threshold_to")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(60, 180, 111, 20))
        self.label_5.setObjectName("label_5")
        self.le_false_positive_penalty = QtWidgets.QLineEdit(self.centralwidget)
        self.le_false_positive_penalty.setGeometry(QtCore.QRect(214, 180, 113, 20))
        self.le_false_positive_penalty.setObjectName("le_false_positive_penalty")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 60, 91, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 100, 91, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 140, 171, 20))
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 20, 91, 20))
        self.label.setObjectName("label")
        self.label_progress = QtWidgets.QLabel(self.centralwidget)
        self.label_progress.setGeometry(QtCore.QRect(240, 320, 47, 13))
        self.label_progress.setText("")
        self.label_progress.setObjectName("label_progress")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_6.setText(_translate("MainWindow", "False negative penalty"))
        self.le_false_negative_penalty.setText(_translate("MainWindow", "1"))
        self.pushButton.setText(_translate("MainWindow", "OK"))
        self.le_threshold_from.setText(_translate("MainWindow", "0.1"))
        self.le_threshold_step.setText(_translate("MainWindow", "0.1"))
        self.le_min_dice.setText(_translate("MainWindow", "0.1"))
        self.le_threshold_to.setText(_translate("MainWindow", "0.9"))
        self.label_5.setText(_translate("MainWindow", "False positive penalty"))
        self.le_false_positive_penalty.setText(_translate("MainWindow", "1"))
        self.label_2.setText(_translate("MainWindow", "Threshold to"))
        self.label_3.setText(_translate("MainWindow", "Threshold step"))
        self.label_4.setText(_translate("MainWindow", "Minimum Dice coeff for overlap"))
        self.label.setText(_translate("MainWindow", "Threshold from"))
